//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePomodoro.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimplePomodoro.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of the break phase must be between {0} and {1} minutes..
        /// </summary>
        internal static string Error_BreakPhaseOutOfRange {
            get {
                return ResourceManager.GetString("Error_BreakPhaseOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse &quot;{0}&quot;..
        /// </summary>
        internal static string Error_CannotParse {
            get {
                return ResourceManager.GetString("Error_CannotParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of cycles before a long break must be between {0} and {1}..
        /// </summary>
        internal static string Error_CyclesBeforeLongBreakOutOfRange {
            get {
                return ResourceManager.GetString("Error_CyclesBeforeLongBreakOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cycles must be between {0} and {1}..
        /// </summary>
        internal static string Error_CyclesCountOutOfRange {
            get {
                return ResourceManager.GetString("Error_CyclesCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect value..
        /// </summary>
        internal static string Error_IncorrectValue {
            get {
                return ResourceManager.GetString("Error_IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of the long break phase must be between {0} and {1} minutes..
        /// </summary>
        internal static string Error_LongBreakPhaseOutOfRange {
            get {
                return ResourceManager.GetString("Error_LongBreakPhaseOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be found..
        /// </summary>
        internal static string Error_PathNotFound {
            get {
                return ResourceManager.GetString("Error_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown field..
        /// </summary>
        internal static string Error_UnknownField {
            get {
                return ResourceManager.GetString("Error_UnknownField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The duration of the work phase must be between {0} and {1} minutes..
        /// </summary>
        internal static string Error_WorkPhaseOutOfRange {
            get {
                return ResourceManager.GetString("Error_WorkPhaseOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value of the break phase: {0}..
        /// </summary>
        internal static string Info_BreakPhaseValue {
            get {
                return ResourceManager.GetString("Info_BreakPhaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current amount of cycles before the long break: {0}..
        /// </summary>
        internal static string Info_CyclesBeforeLongBreakValue {
            get {
                return ResourceManager.GetString("Info_CyclesBeforeLongBreakValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current amount of cycles: {0}..
        /// </summary>
        internal static string Info_CyclesCountValue {
            get {
                return ResourceManager.GetString("Info_CyclesCountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value of the long break phase: {0}..
        /// </summary>
        internal static string Info_LongBreakPhaseValue {
            get {
                return ResourceManager.GetString("Info_LongBreakPhaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current music directory: {0}..
        /// </summary>
        internal static string Info_MusicDirValue {
            get {
                return ResourceManager.GetString("Info_MusicDirValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new value was set successfully..
        /// </summary>
        internal static string Info_ValueSetSuccessfully {
            get {
                return ResourceManager.GetString("Info_ValueSetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value of the work phase: {0}..
        /// </summary>
        internal static string Info_WorkPhaseValue {
            get {
                return ResourceManager.GetString("Info_WorkPhaseValue", resourceCulture);
            }
        }
    }
}
